// File generated by Custom Setup for businessapp-1786e
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDummyKeyForBusinessApp1786e", // مفتاح مشروعك
    appId: "1:1000000000000:web:abcdef123456789",
    messagingSenderId: "1000000000000",
    projectId: "businessapp-1786e",
    storageBucket: "businessapp-1786e.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDummyKeyForBusinessApp1786e",
    appId: "1:1000000000000:android:abcdef123456789",
    messagingSenderId: "1000000000000",
    projectId: "businessapp-1786e",
    storageBucket: "businessapp-1786e.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDummyKeyForBusinessApp1786e",
    appId: "1:1000000000000:ios:abcdef123456789",
    messagingSenderId: "1000000000000",
    projectId: "businessapp-1786e",
    storageBucket: "businessapp-1786e.appspot.com",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyDummyKeyForBusinessApp1786e",
    appId: "1:1000000000000:macos:abcdef123456789",
    messagingSenderId: "1000000000000",
    projectId: "businessapp-1786e",
    storageBucket: "businessapp-1786e.appspot.com",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDummyKeyForBusinessApp1786e",
    appId: "1:1000000000000:windows:abcdef123456789",
    messagingSenderId: "1000000000000",
    projectId: "businessapp-1786e",
    storageBucket: "businessapp-1786e.appspot.com",
  );
}
